CREATE USER gameLotto WITH LOGIN CREATEDB PASSWORD '123';
CREATE DATABASE gameLotto WITH OWNER gameLotto;

CREATE TABLE "user" ("id" SERIAL PRIMARY KEY, "name" VARCHAR);


ALTER TABLE "user" ADD COLUMN "last_name" VARCHAR DEFAULT 'found';

ALTER TABLE "user" DROP COLUMN "last_name";

DROP TABLE "user";

ALTER TABLE "user" ADD COLUMN "age" INT DEFAULT 20;